services:
  ai-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-model-api
    ports:
      - "8001:8001"
    environment:
      HOST: 0.0.0.0
      PORT: 8001
      UVICORN_RELOAD: "false"
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    external: true
    name: fieldforce_network